### ISSUE TITLE
CSS trouble because of JS-injected stylesheet 

### ISSUE THREAD

**Issue by rsaccon** [developit/preact-mdl#1]
I just started to use preact and preact-mdl and like it very much so far. However I had some trouble customizing styles. I am using npm. Is there a convincing reason why you inject the MDL stylesheet via JS `__$styleInject` (as part your build-toolchain) ? Well, one HTTP request less. But customizing styles, e.g. positioning fab buttons then needs `!important`, at least when using normal stylesheets. And how do I use an alternative stylesheet with different color theme ? The stylesheet also gets loaded later (the JS must be loaded and parsed first)

btw. a few days ago, MDL 1.1.1 got released, with Lists, Dialogs, Snackbar/Toast components.

**Comment by developit** [comment]
Hmm. You shouldn't have to use `!important` to override, but you would have to specify a selector with higher precedence than the mdl ones.

To that end though, I'd like to be able to ship the JS standalone.  Right now people using `preact-mdl` are dependent on it to pull in new versions of MDL, which is suboptimal.

I'm not sure what the best approach would be for bundling VS just including the JS.  Perhaps two files in the root so you could do:

``` js
import { Button } from 'preact-mdl/standalone';
```

... though that is a lot of repetition throughout your code.

Maybe a second NPM module like `preact-mdl-wrapper` would be better?

Let me know your thoughts!

> -- edit --
> 
> When you posted this, I thought "that's weird, I don't have that issue", and then I realized that I have just been pulling `preact-mdl` into my repos to solve this very problem:
> 
> https://github.com/developit/nectarine/blob/master/src/style/mdl.less
> 
> So I'm keen on a better solution since I'm apparently experiencing the same thing, haha.

**Comment by rsaccon** [comment]
About custom color themes, took another look at the MDL NPM package. All possible color combination based themes are also there, in the dist folder, so no need to load them from google CDN. But if one wants to make a mobile/desktop app and not a website, then also the Fonts and Material icons need to be bundled into the app css, and this is a bit quirky now.

**Comment by developit** [comment]
Agreed. The way I'm getting around that for now is by bundling via webpack using url-loader.

**Comment by developit** [comment]
@rsaccon Maybe `preact-mdl` should just export the module and users are responsible for including the MDL CSS and JS into their build process?

**Comment by rsaccon** [comment]
@developit That probably is the most flexible solution, and if it is documented, the google-suggested way of CDN hosting or otherwise all what needs to be included in custom build process, no one will run into issues about this anymore, hopefully.

**Comment by unindented** [comment]
+1 to the idea of not requiring `material-design-lite`'s CSS and JS here, and letting people handle that.

**Comment by developit** [comment]
@unindented Do you think it's worth keeping this module bundled and creating a second unbundled one? Trying to think of how to transition to non-bundled JS and CSS without just calling it a breaking change and letting people fend for themselves, haha.

**Comment by unindented** [comment]
@developit I don't know how many people are using this module. If you think it would disturb too many people, then creating a different module may be the right call. Otherwise, maybe you can bump the minor version so that they don't accidentally update to this new approach, and avoid creating a new module. Mo' modules, mo' confusion.

**Comment by developit** [comment]
I just published `1.0.0`, which no longer include MDL.  It'll try to reference `componentHandler` off of window (MDL puts it there), otherwise you can set `options.mdl` or `options.componentHandler` to your local reference to it.

**Comment by developit** [comment]
Closing this issue for now but please feel free to discuss, I'd still like to dream up a way to ship a "ready to go" version of this instead of needing a boilerplate project.

**Comment by unindented** [comment]
:+1:
