### ISSUE TITLE
Relax preact version?

### ISSUE THREAD

**Issue by unindented** [developit/preact-mdl#10]
Should we relax the version of the `preact` peer dependency, so that `preact-mdl` can be used with `4.x.x` too?

**Comment by developit** [comment]
Good catch, I have been doing the rounds fixing this in other `preact-*` repos.  I think the only one that legitimately needs to not be `*` is `preact-compat`.

This is released as `1.2.1` btw.

**Comment by developit** [comment]
I should add - I have been using a local copy of `preact-mdl` in Nectarine as one of my "real-world" tests for Preact 4, so there shouldn't be any issues.  If anything, the performance and memory usage is vastly improved :)

**Comment by unindented** [comment]
Sounds awesome, I'll try today.
