### ISSUE TITLE
 Cannot read property 'upgradeElement' of undefined

### ISSUE THREAD

**Issue by sbehrends** [developit/preact-mdl#17]
Any component im trying to use i get

```
Cannot read property 'upgradeElement' of undefined
```

in the line:

```
if (this.base && this.base.parentElement) {
this.upgradedBase = this.base;
mdl().upgradeElement(this.base);
}
```

installed depencies

```
    "material-design-lite": "^1.2.0",
    "preact": "^5.7.0",
    "preact-mdl": "^1.3.0",
```

**Comment by developit** [comment]
@sbehrends might be an issue with mdl 1.2, I will check as soon as I can! 

Just I know - have you somehow included the mdl JavaScript into the page? I do this via a side effect import but it can also just be a script tag.

**Comment by sbehrends** [comment]
I didn't. Sadly the Readme does not explaing how to use it.
I expected something like this. I guess i'll try to add the mdl js in the html.

```
const { Button } from 'preact-mdl;
<Button />
```

**Comment by developit** [comment]
Sorry, we actually used to automatically bundle it but as a group decided to take that out, since it broke themes. I should update the readme to explain that as part of the install!

**Comment by sbehrends** [comment]
I added it to the bundle and now works properly. Anything else I should add besided this js and css?

**Comment by developit** [comment]
Nope, that's it! Sorry for the confusion. 😅
