### ISSUE TITLE
Are menus working ?

### ISSUE THREAD

**Issue by rsaccon** [developit/preact-mdl#2]
It does not open in my test, when clicking on button, this is how I have wired it up:

```
<Button id="demo" icon><Icon icon="more_vert" /></Button>
<Menu for="demo" bottom-right={ true } bottom-left={ false }>
  <Menu.Item>Foo</Menu.Item>
  <Menu.Item disabled={ true }>Bar</Menu.Item>
</Menu>
```

**Comment by developit** [comment]
Hi @rsaccon - MDL's wiring for setting up button<->menu click events does not support dynamically rendered components.  In my own projects, I am using the following setup to toggle them:

``` js
function toggleMenu(e) {
  let menu = e.target.parentNode.querySelector('.mdl-menu');
  if (menu) menu.MaterialMenu.toggle();
  e.preventDefault();
}
```

In your example, this would be:

``` js
<Button icon onClick={toggleMenu}><Icon icon="more_vert" /></Button>
<Menu bottom-right>
  <Menu.Item>Foo</Menu.Item>
  <Menu.Item disabled>Bar</Menu.Item>
</Menu>
```

_(side note: `<a foo={true}>` and `<a foo>` do the same thing)_

**Comment by rsaccon** [comment]
ok, thanks a lot, now it works halfway as expected. But I had to adapt the dom query:

`let menu = e.target.parentNode.parentNode.querySelector('.mdl-menu');`

unfortunately the alignment options seem to have no effect, and when I click anywhere outside the menu, it does not close (but toggling the button, off course works)

**Comment by developit** [comment]
@rsaccon are you calling preventDefault() in a delegated even handler somewhere?  I'm using this exact technique in Nectarine and clicking outside the menu closes it: https://github.com/developit/nectarine/blob/master/src/components/post/comment.js#L39-L45

**Comment by rsaccon** [comment]
@developit thanks again, now clicking outside works as well, just alignment not yet, and I have them wired up as in nectarine, where it seems to work perfectly

**Comment by developit** [comment]
I was having issues with alignment too.  Make sure you are setting `position` `relative` or `absolute` on the parent element in order for their offsets to work. 

Closing but please keep me posted on the positioning, since I believe I ended up overriding it in Nectarine.

**Comment by rsaccon** [comment]
Ok, all fine now. Thanks a lot again. I use a wrapper, where I can optional set alignment class (without, it aligns left)

```
<div class="menu-wrap right">
  <Button id="demo-menu-right"
    onClick={ toggleMenu }
    icon><Icon icon="more_vert" /></Button>
  <Menu for="demomenurigth">
    <Menu.Item>Foo</Menu.Item>
    <Menu.Item disabled>Bar</Menu.Item>
  </Menu>
</div>
```

and this is the css:

```
.menu-wrap {
    position: relative;
}

.menu-wrap.right .mdl-menu__container {
  right: 0;
}
```

**Comment by developit** [comment]
Looks good. Only thing I'd mention is just to remember IDs are supposed to be document-unique, and since you're triggering the menu toggling programmatically you can drop both `id` and `for`. Cheers.
