### ISSUE TITLE
Latest `preact`

### ISSUE THREAD

**Issue by unindented** [developit/preact-mdl#3]
Can this project be updated to use the latest `preact` version, or are they incompatible?

**Comment by developit** [comment]
Ah yes it can - sorry I must have missed in when doing the rounds after releasing 3.0.

**Comment by developit** [comment]
@unindented Just released [version `0.3.0`](https://github.com/developit/preact-mdl/releases/tag/0.3.0) which switches to allowing any version of Preact as a peer dependency.

**Comment by unindented** [comment]
:+1:
