### ISSUE TITLE
className of instance

### ISSUE THREAD

**Issue by prateekbh** [developit/preact-mdl#33]
<Button icon className="xyz"></Button> should get appended to generated markup's class name list

working without this, makes it a little painful to target components

**Comment by developit** [comment]
In addition to the MDL classes you mean?

**Comment by prateekbh** [comment]
Yep

**Comment by developit** [comment]
Seems nice. Could also make it an attribute: `data-mdl-component="button"`. Want to PR?

**Comment by prateekbh** [comment]
Yess  :) would love to

**Comment by prateekbh** [comment]
this issue is not reproducable in an isolated repo, closing for now
