### ISSUE TITLE
Isomorphic / Server-side rendering support

### ISSUE THREAD

**Issue by BerndWessels** [developit/preact-mdl#38]
Hi @developit 
Any idea if there is a way to make this render or at least not break server-side?
It looks like `mdl` needs the global `window` which obviously doesn't exist in `node`.
Basically we want the html to be rendered, but nothing of the browser specific `window` stuff should happen server-side. Is there a kind of `unwindow` (like `undom`) or so?
I would really like to know your thoughts on this, thanks.

**Comment by developit** [comment]
Ah that's a good point. Ideally we could just wrap the MDL import in a check for `typeof window!='undefined'`. Think that'd work?

**Comment by BerndWessels** [comment]
How would that work? Is that something to be done within `preact-mdl` or outside of it?

**Comment by BerndWessels** [comment]
@developit This works but I would like to know if you think it is the right way to get it to work or if there is a better way:

Only tested with <Button> yet.

```js
import {h, Component} from 'preact';
import {Button} from 'preact-mdl';
var mdl = {
  downgradeElements: () => {},
  upgradeElement: () => {}
}
if (process.env.WEB) {
  mdl = require('material-design-lite/material');
}
// this now allows server side rendering of <Button> without breaking.
```

**Comment by developit** [comment]
ah - I had forgotten it'd still try to call those methods. The `process.env.WEB` bit is probably as good as we could do, or if you wanted to detect nodejs you could do something like:

```js
if (typeof window=='undefined') {
  global.window = global.window || global;
  global.mdl = {
    downgradeElements: () => {},
    upgradeElement: () => {}
  };
}
else {
  require('material-design-lite/material');
}
```

**Comment by BerndWessels** [comment]
OK, so for now you think this is a reasonable way to do it?

It seems to work but I have to try some more components to be sure.

**Comment by developit** [comment]
Yup, I think that would work fairly well. It won't include the MDL-generated elements, which makes sense since they are only for manipulation via JS and will get generated on the client.

**Comment by BerndWessels** [comment]
OK, great thanks.
