### ISSUE TITLE
mdl-layout__obfuscator does not remove is-visible class

### ISSUE THREAD

**Issue by angelsalazar-zz** [developit/preact-mdl#45]
Hi,
I run into this problem whem using the component Layout.Drawer on small devices.

The problem is basically that the div with class 'mdl-layout__obfuscator' (the gray overlay) some times keeps the class 'is-visible' when the drawer is closed.

I have reproduce this issue and you can find the link below
[Link](https://jsfiddle.net/1gqxexfn/)

I am using 
material-design-lite version 1.3.0
preact version 8.2.1
preact-mdl version 2.2.1
preact-router version 2.5.5

**Comment by johnhorsema** [comment]
I have the same issue with my project.

**Comment by developit** [comment]
FWIW I generally use the Drawer with `js={false}` and control the `is-visible` class myself.
Example: https://github.com/developit/nectarine/blob/master/src/components/sidebar.js#L58

**Comment by angelsalazar-zz** [comment]
thank you
